### ISSUE TITLE
 lack of funds

### ISSUE THREAD

**Issue by andrzejkp** [mvs-org/lightwallet#102]
Hello, today I logged into a light wallet and it turned out that there is no money in my account. On January 30, I deposited a certain amount of money on the wallet after the withdrawal transaction from the exchange, I checked the light wallet and it was all right. But today I am blinking my eyes because there is no transaction in history and the balance is zero. What happens that my etp disappears ????

**Comment by canguruhh** [comment]
hi andrzejkp,
the network is currently experiencing difficulties because of a network split. However if you deposited the ETP already in Jan you should see it on the lightwallet. Please click on receive and verify that it lists the address you used for the exchange withdrawal. Is you cant find it you might not use the correct key file. You can also try to recreate the wallet from the backup words if that case. If you find it and the tx are not there then please wait until the network problems are resolved or provide some information about a missing transaction.

**Comment by andrzejkp** [comment]
![scrin](https://user-images.githubusercontent.com/37432112/37506030-53fd40e6-28e8-11e8-8f8c-3dd5dc0709fe.png)

**Comment by canguruhh** [comment]
Ok. If the explorer has the tx it must be on the blockchain. Please check if your lightwallet lists the address

**Comment by andrzejkp** [comment]
Hi, thank you for your quick response, after several attempts I managed to see the funds as it should be :) is already ok. Can you tell me what happened to hardfork? such information appeared, what does this mean for me?

**Comment by canguruhh** [comment]
please wait with creating new transactions until the network stabilizes. just to avoid problems because transactions might become invalid if the chain splits. there will be an announcement as soon as its fixed. The funds are safe on the wallet anyway.

**Comment by andrzejkp** [comment]
and how will it separate then I will have more etp?

**Comment by canguruhh** [comment]
no. the blockchain splits but not the coins. unless users create transactions during this period they will not be affected at all. only if you create a transaction now you will later have to check if your transaction really worked.

**Comment by andrzejkp** [comment]
Thank you very much. Best wishes

**Comment by canguruhh** [comment]
you are welcome
