### ISSUE TITLE
Improve sliders handling

### ISSUE THREAD

**Issue by LaurentSalou** [mvs-org/lightwallet#209]
Currently depending on the platform the sliders sometimes don't update correctly the values when using drag and drop (i.e. in asset creation or avatar creation).
Also, in avatar creation if the advanced option is disabled, it keep the value selected via the slider.

**Comment by canguruhh** [comment]
It might be related to angular materials gesture support. see the 5th step of the installation manual:

Step 5: Gesture Support

Some components (mat-slide-toggle, mat-slider, matTooltip) rely on HammerJS for gestures. In order to get the full feature-set of these components, HammerJS must be loaded into the application.

You can add HammerJS to your application via npm, a CDN (such as the Google CDN), or served directly from your app.

To install via npm, use the following command:
NPM

npm install --save hammerjs

Yarn

yarn add hammerjs

After installing, import it on your app's entry point (e.g. src/main.ts).

import 'hammerjs';

**Comment by canguruhh** [comment]
Please update this issues status

**Comment by canguruhh** [comment]
Pushed a fix for asset transfer page fee slider. To be added to the other pages.

**Comment by LaurentSalou** [comment]
Fix applied to all the sliders
